# .streamlit/secrets.toml

GITHUB_TOKEN = "ghp_yourgithubtokenhere"
GITLAB_TOKEN = "glpat-yourgitlabtokenhere"
GMAIL_CLIENT_ID = "your-google-client-id"
GMAIL_CLIENT_SECRET = "your-google-client-secret"
GMAIL_REFRESH_TOKEN = "your-google-oauth-refresh-token"
