# .streamlit/secrets.toml

import streamlit as st
from github import Github
import gitlab

# Load secrets
GITHUB_TOKEN = st.secrets["GITHUB_TOKEN"]
GITLAB_TOKEN = st.secrets["GITLAB_TOKEN"]
GITLAB_PROJECT_ID = st.secrets["GITLAB_PROJECT_ID"]
GITLAB_URL = st.secrets.get("GITLAB_URL", "https://gitlab.com")
GMAIL_CLIENT_ID = "your-google-client-id"
GMAIL_CLIENT_SECRET = "your-google-client-secret"
GMAIL_REFRESH_TOKEN = "your-google-oauth-refresh-token

st.header("Bala Coding Agent Integration Demo")

# --- GitHub Connection ---
try:
    g = Github(GITHUB_TOKEN)
    gh_user = g.get_user()
    st.success(f"Connected to GitHub as: {gh_user.login}")
except Exception as e:
    st.error(f"GitHub Connection error: {e}")

# --- GitLab Connection ---
try:
    gl = gitlab.Gitlab(GITLAB_URL, private_token=GITLAB_TOKEN)
    gl.auth()
    # Get project (can use project path or ID)
    project = gl.projects.get(GITLAB_PROJECT_ID)
    st.success(f"Connected to GitLab project: {project.name} ({project.path_with_namespace})")
    st.write(f"Website: {project.web_url}")
except Exception as e:
    st.error(f"GitLab Connection error: {e}")

# --- Example: List files in GitLab project repository ---
if 'project' in locals():
    st.subheader("Files in root directory:")
    files = project.repository_tree(path='', ref='main')
    for f in files:
        st.write(f"{f['type']}: {f['name']}")
